<section class="content-header">
    
    <ol class="breadcrumb left">
       <i class="icon-envelope"></i> Contato
    </ol>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="conteudo">
                <div class="row">

                    <!-- quick email widget -->
                    <div class="box">

                        <div class="box-header">                            

                            <h3 class="box-title">Email <i class="icon-envelope"></i></h3>

                        </div>
                        <div class="box-header">                            

                            <?php echo $Contato_statusEmail; ?>

                        </div>
                        <div class="box-body">
                            <form class="form-actions" action="/contato" method="post">
                                <div class="form-group">
                                    <input type="text" class="form-control" name="nome" placeholder="Nome:"
                                           value="<?php echo $nome; ?>"/>
                                </div>
                                <div class="form-group">
                                    <input type="email" class="form-control" name="email" placeholder="Email:"
                                           value="<?php echo $email; ?>"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="assunto" placeholder="Assunto"
                                           value="<?php echo $assunto; ?>"/>
                                </div>
                                <div class="form-group">
                                    <textarea class="form-control" name="mensagem" placeholder="Mensagem"
                                              style="width: 90%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">
                                                  <?php echo $mensagem; ?>
                                    </textarea>
                                </div>
                                <div class="box-footer clearfix">
                                    <a class="pull-left btn btn-default" href="/cliente">
                                        <i class="icon-circle-arrow-left"></i>Voltar</a>                                
                                    <button class="pull-right btn btn-default" id="sendEmail">Enviar <i
                                            class="icon-circle-arrow-right"></i></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
